// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using diet_tracker_api.DataLayer;

#nullable disable

namespace diet_tracker_api.Migrations
{
    [DbContext(typeof(DietTrackerDbContext))]
    [Migration("20251127040535_ChangeWhenToTimestampWithoutTimeZone")]
    partial class ChangeWhenToTimestampWithoutTimeZone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.Fueling", b =>
                {
                    b.Property<int>("FuelingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FuelingId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("FuelingId");

                    b.ToTable("fuelings", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<int>("FuelingCount")
                        .HasColumnType("integer");

                    b.Property<int>("MealCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("PlanId");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("Autosave")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WaterSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(8);

                    b.Property<int>("WaterTarget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(64);

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserDailyTrackingValue", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("Day")
                        .HasColumnType("date");

                    b.Property<int>("UserTrackingValueId")
                        .HasColumnType("integer");

                    b.Property<int>("Occurrence")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("When")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId", "Day", "UserTrackingValueId", "Occurrence");

                    b.HasIndex("UserTrackingValueId");

                    b.ToTable("user_daily_tracking_values", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserDay", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("Day")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Water")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("UserId", "Day");

                    b.ToTable("user_days", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserFueling", b =>
                {
                    b.Property<int>("UserFuelingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserFuelingId"));

                    b.Property<DateTime>("Day")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("When")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserFuelingId");

                    b.HasIndex("UserId", "Day");

                    b.ToTable("user_fuelings", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserMeal", b =>
                {
                    b.Property<int>("UserMealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserMealId"));

                    b.Property<DateTime>("Day")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("When")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserMealId");

                    b.HasIndex("UserId", "Day");

                    b.ToTable("user_meals", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserPlan", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(250)");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId", "PlanId", "Start");

                    b.HasIndex("PlanId");

                    b.ToTable("user_plans", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserTracking", b =>
                {
                    b.Property<int>("UserTrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTrackingId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<bool>("UseTime")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(250)");

                    b.HasKey("UserTrackingId");

                    b.HasIndex("UserId");

                    b.ToTable("user_trackings", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserTrackingValue", b =>
                {
                    b.Property<int>("UserTrackingValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTrackingValueId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserTrackingId")
                        .HasColumnType("integer");

                    b.HasKey("UserTrackingValueId");

                    b.HasIndex("UserTrackingId");

                    b.ToTable("user_tracking_values", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserTrackingValueMetadata", b =>
                {
                    b.Property<int>("UserTrackingValueId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserTrackingValueId", "Key");

                    b.ToTable("user_tracking_value_metadata", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.Victory", b =>
                {
                    b.Property<int>("VictoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VictoryId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("When")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("VictoryId");

                    b.HasIndex("UserId");

                    b.ToTable("victories", (string)null);
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserDailyTrackingValue", b =>
                {
                    b.HasOne("diet_tracker_api.DataLayer.Models.UserTrackingValue", "TrackingValue")
                        .WithMany("DailyTrackingValues")
                        .HasForeignKey("UserTrackingValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("diet_tracker_api.DataLayer.Models.UserDay", "UserDay")
                        .WithMany("TrackingValues")
                        .HasForeignKey("UserId", "Day")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackingValue");

                    b.Navigation("UserDay");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserDay", b =>
                {
                    b.HasOne("diet_tracker_api.DataLayer.Models.User", "User")
                        .WithMany("UserDays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserFueling", b =>
                {
                    b.HasOne("diet_tracker_api.DataLayer.Models.User", null)
                        .WithMany("UserFuelings")
                        .HasForeignKey("UserId");

                    b.HasOne("diet_tracker_api.DataLayer.Models.UserDay", "UserDay")
                        .WithMany("Fuelings")
                        .HasForeignKey("UserId", "Day");

                    b.Navigation("UserDay");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserMeal", b =>
                {
                    b.HasOne("diet_tracker_api.DataLayer.Models.User", null)
                        .WithMany("UserMeals")
                        .HasForeignKey("UserId");

                    b.HasOne("diet_tracker_api.DataLayer.Models.UserDay", "UserDay")
                        .WithMany("Meals")
                        .HasForeignKey("UserId", "Day");

                    b.Navigation("UserDay");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserPlan", b =>
                {
                    b.HasOne("diet_tracker_api.DataLayer.Models.Plan", "Plan")
                        .WithMany("UserPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("diet_tracker_api.DataLayer.Models.User", "User")
                        .WithMany("UserPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserTracking", b =>
                {
                    b.HasOne("diet_tracker_api.DataLayer.Models.User", "User")
                        .WithMany("UserTrackings")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserTrackingValue", b =>
                {
                    b.HasOne("diet_tracker_api.DataLayer.Models.UserTracking", "Tracking")
                        .WithMany("Values")
                        .HasForeignKey("UserTrackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tracking");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserTrackingValueMetadata", b =>
                {
                    b.HasOne("diet_tracker_api.DataLayer.Models.UserTrackingValue", "UserTrackingValue")
                        .WithMany("Metadata")
                        .HasForeignKey("UserTrackingValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTrackingValue");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.Victory", b =>
                {
                    b.HasOne("diet_tracker_api.DataLayer.Models.User", "User")
                        .WithMany("Victories")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.Plan", b =>
                {
                    b.Navigation("UserPlans");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.User", b =>
                {
                    b.Navigation("UserDays");

                    b.Navigation("UserFuelings");

                    b.Navigation("UserMeals");

                    b.Navigation("UserPlans");

                    b.Navigation("UserTrackings");

                    b.Navigation("Victories");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserDay", b =>
                {
                    b.Navigation("Fuelings");

                    b.Navigation("Meals");

                    b.Navigation("TrackingValues");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserTracking", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("diet_tracker_api.DataLayer.Models.UserTrackingValue", b =>
                {
                    b.Navigation("DailyTrackingValues");

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
